### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by Lewiscowles1986** [ataylorme/WordPress-Hosting-Best-Practices-Documentation#11]
So this should probably be broken into sub issues as well as the main issue. But it'd be nice to have examples contributed to assist people to visualise best-practices.

**Comment by ataylorme** [comment]
Hi @Lewiscowles1986. Thanks for adding your input! Examples are something of a gray area. While we want to explain topics in detail and their benefits we've avoided having implementation examples for a few reasons:

* It might not work for everyone. Each hosting environment is different. From operating system to installed packages, etc. It would be tough, if not impossible, to create a tutorial/example that worked for everyone
* Maintenance would become a much larger commitment. Currently we are trying to keep the content evergreen so that it is always relevant and lessens the maintenance burden of this volunteer effort.
* Implementation resources are readily available elsewhere

I'm happy to hear more pros to giving detailed, specific examples. The decision to not provide them isn't set in stone but something we may reconsider later if there is a valid argument but right now the focus is on finishing the core content.
